const orders = [{
        id: 1,
        name: 'Fortune King',
        email: 'kingstonfortune@gmail.com',
        meal: 'rice',
        quantity: 1,
        price: 200,
        location: 'Lekki, Lagos',
        created_at: 'Sun Aug 26 2018',
        status: 'completed',
    },
    {
        id: 2,
        name: 'John Doe',
        email: 'john@doe.com',
        meal: 'egusi soup',
        quantity: 2,
        price: 400,
        location: 'Kaduna',
        created_at: 'Sun Aug 26 2018',
        status: 'pending',
    },
    {
        id: 3,
        name: 'Ire Timi',
        email: 'timigod@ire.com',
        meal: 'sharwarma',
        quantity: 2,
        price: 2400,
        location: 'Silicon Valley',
        created_at: 'Sat Oct 03 2037',
        status: 'pending',
    },
];

export default orders;